### ISSUE TITLE
review metadata

### ISSUE THREAD

**Issue by csae8092** [arthur-schnitzler/pmb-ingest#1]
just in case you care, if not, just close the issue

I set up a ingestion workflow to archive pmb-dumps in ARCHE; all metadata can be changed in https://github.com/arthur-schnitzler/pmb-ingest/blob/main/to_ingest/arche.ttl

feel free to add/correct/whatever

see here how it will look like https://id.acdh.oeaw.ac.at/pmb

**Comment by martinantonmueller** [comment]
I do care! Great stuff!
